# Generated by Django 5.2.5 on 2025-11-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='due_at',
        ),
        migrations.AddField(
            model_name='reminder',
            name='due_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='reminder',
            name='due_time',
            field=models.TimeField(default=None),
        ),
    ]
