# Generated by Django 5.2.5 on 2025-11-02 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_reminder_due_at_reminder_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='due_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
