# Generated by Django 5.2.5 on 2025-11-02 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_reminder_due_date_alter_reminder_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='due_time',
            field=models.TimeField(default=datetime.datetime.now, null=True),
        ),
    ]
